/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
  aws_project_region: "us-east-2",
  aws_cognito_identity_pool_id:
    "us-east-2:55402f85-9839-4299-86bb-76e66e0c6718",
  aws_cognito_region: "us-east-2",
  aws_user_pools_id: "us-east-2_1GjwHo9LB",
  aws_user_pools_web_client_id: "79jclhbatcksmfsq6rm5d7sr93",
  oauth: {},
  aws_appsync_graphqlEndpoint:
    "https://t5apma52ezfq3nz4v5rgi7zkyy.appsync-api.us-east-2.amazonaws.com/graphql",
  aws_appsync_region: "us-east-2",
  aws_appsync_authenticationType: "AMAZON_COGNITO_USER_POOLS",
  aws_appsync_apiKey: "da2-nd2p6xrzzjb45oike2rixrd46u",
};

export default awsmobile;
